### PR TITLE
Deep insert java

### PR DESCRIPTION
**Pull request by princeneil**
CAP example for deep insert with Java OData v2 issue

### CODE REVIEW

**Comment by gregorwolf** [comment]
I've tried your example a bit. Unfortunately the JSON in the readme for the POST isn't valid. Please also correct this.

**Comment by princeneil** [comment]
@gregorwolf - I've corrected the JSON in the readme (as well as another typo). Apologies.

**Comment by princeneil** [comment]
@vobu - I've removed the project.json file from / . My commit added to the .gitignore but it was existing (2 previous commits). Do you want me to remove my changes and leave the file? or remove the file?

**Comment by vobu** [comment]
> @vobu - I've removed the project.json file from / . My commit added to the .gitignore but it was existing (2 previous commits). Do you want me to remove my changes and leave the file? or remove the file?

nah, that's fine. I'll merge this now.

**Pull request merged**
